#!/bin/bash
# ============================================================================
# 📋 FastAPI Video API - Deployment Checklist
# ============================================================================
# Follow these steps to deploy to your Hostinger VPS
# Check off each item as you complete it
# ============================================================================

echo ""
echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║         🚀 FASTAPI VIDEO API - DEPLOYMENT CHECKLIST                       ║"
echo "║             Deploy to Any Hostinger VPS in 5 Minutes!                    ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""

# Colors
OK="✅"
PENDING="⏳"
INSTRUCTIONS="▶️"

echo "PHASE 1: PREPARATION (Do this on your local machine)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "$PENDING STEP 1: Edit deployment configuration"
echo "         File: deployment/deploy.conf"
echo "         Todo:"
echo "           [ ] Set DEPLOY_DIR (default: /var/www/fastapi-video-api)"
echo "           [ ] Set SERVICE_NAME (default: fastapi-video-api)"
echo "           [ ] Set INTERNAL_PORT (default: 8000, change if conflict)"
echo "           [ ] Set DOMAIN_NAME (your actual domain)"
echo "           [ ] Set SESSION_SECRET (your API key)"
echo ""
echo "         Save the file after editing"
echo ""

echo "$PENDING STEP 2: Commit configuration to git"
echo "         Commands:"
echo "           git add deployment/deploy.conf"
echo "           git commit -m 'Add deployment configuration'"
echo "           git push"
echo ""
echo "         ℹ️  This ensures you can deploy to any server anytime"
echo ""

echo "PHASE 2: DEPLOYMENT (Execute on your Hostinger VPS)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "$PENDING STEP 3: SSH into your Hostinger VPS"
echo "         Command:"
echo "           ssh root@YOUR_SERVER_IP"
echo ""
echo "         Example:"
echo "           ssh root@147.93.27.148"
echo ""

echo "$PENDING STEP 4: Clone your project"
echo "         Command:"
echo "           git clone https://github.com/YOUR_USERNAME/apiXVideo /var/www/apiXVideo"
echo ""

echo "$PENDING STEP 5: Make scripts executable"
echo "         Commands:"
echo "           cd /var/www/apiXVideo"
echo "           chmod +x deployment/*.sh"
echo ""

echo "$PENDING STEP 6: Run deployment (choose one)"
echo ""
echo "         OPTION A - Fast mode (recommended, uses config file)"
echo "           sudo ./deployment/deploy_openlitespeed.sh --fast"
echo ""
echo "         OPTION B - Interactive mode (asks questions)"
echo "           sudo ./deployment/deploy_openlitespeed.sh"
echo ""
echo "         ⏱️  Wait 5 minutes for deployment to complete..."
echo ""

echo "PHASE 3: VERIFICATION (After deployment completes)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "$PENDING STEP 7: Check service status"
echo "         Command:"
echo "           sudo systemctl status fastapi-video-api"
echo ""
echo "         Expected: ● fastapi-video-api.service - Loaded ● active (running)"
echo "         [ ] Service is running"
echo ""

echo "$PENDING STEP 8: Run health check"
echo "         Command:"
echo "           ./deployment/health-check.sh"
echo ""
echo "         Expected: All checks should show ✓"
echo "         [ ] All health checks pass"
echo ""

echo "$PENDING STEP 9: Test API locally"
echo "         Command:"
echo "           curl http://localhost:8000/"
echo ""
echo "         Expected: JSON response with status: healthy"
echo "         [ ] API responds with 200 status"
echo ""

echo "PHASE 4: CYBERPANEL CONFIGURATION (On CyberPanel WebAdmin)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "$PENDING STEP 10: Add External App in CyberPanel"
echo "           Location: WebAdmin Console → Server Configuration → External App"
echo "           [ ] Click 'Add External App'"
echo "           [ ] Name: fastapi-video-api"
echo "           [ ] Address: 127.0.0.1"
echo "           [ ] Port: 8000 (or your INTERNAL_PORT)"
echo "           [ ] Click 'Save'"
echo ""

echo "$PENDING STEP 11: Add Rewrite Rule for your domain"
echo "           Location: Websites → Your Domain → Rewrite Rules"
echo "           [ ] Copy and paste this:"
echo ""
echo "               RewriteEngine On"
echo "               RewriteCond %{REQUEST_FILENAME} !-f"
echo "               RewriteCond %{REQUEST_FILENAME} !-d"
echo "               RewriteRule ^(.*)$ http://127.0.0.1:8000/\$1 [P,L]"
echo ""
echo "           [ ] Replace 8000 with your INTERNAL_PORT if different"
echo "           [ ] Click 'Save'"
echo ""

echo "$PENDING STEP 12: Enable SSL certificate"
echo "           Location: SSL → Manage SSL → Your Domain"
echo "           [ ] Click 'Issue SSL' (or use existing)"
echo "           [ ] Wait for certificate to be issued"
echo ""

echo "$PENDING STEP 13: Restart OpenLiteSpeed"
echo "           Location: Dashboard → Service Manager"
echo "           [ ] Click 'Restart OpenLiteSpeed'"
echo "           [ ] Wait for restart to complete"
echo ""

echo "PHASE 5: FINAL VERIFICATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "$PENDING STEP 14: Test API externally"
echo "         Command:"
echo "           curl https://yourdomain.com/"
echo ""
echo "         Expected: JSON response with status: healthy"
echo "         [ ] API responds with 200 status"
echo ""

echo "$PENDING STEP 15: Test with API key"
echo "         First, get your API key:"
echo "           cat /var/www/fastapi-video-api/.env | grep SESSION_SECRET"
echo ""
echo "         Then test:"
echo "           curl -H 'X-API-Key: YOUR_KEY' https://yourdomain.com/files"
echo ""
echo "         Expected: JSON with list of files"
echo "         [ ] API key authentication works"
echo ""

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║                         🎉 DEPLOYMENT COMPLETE!                           ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "NEXT STEPS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  Backup your credentials"
echo "    Location: /var/www/fastapi-video-api/CREDENTIALS.txt"
echo "    Save these in a password manager!"
echo ""

echo "2️⃣  Setup regular backups"
echo "    Command: ./deployment/backup.sh"
echo "    Run weekly to backup video data"
echo ""

echo "3️⃣  Monitor your service"
echo "    Command: sudo journalctl -u fastapi-video-api -f"
echo "    Check logs regularly"
echo ""

echo "4️⃣  Test quick recovery process"
echo "    Command: ./deployment/quick-restore.sh"
echo "    Verify you can recover if server fails"
echo ""

echo "USEFUL COMMANDS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "View logs:"
echo "  sudo journalctl -u fastapi-video-api -f"
echo ""

echo "Check health:"
echo "  ./deployment/health-check.sh"
echo ""

echo "Restart service:"
echo "  sudo systemctl restart fastapi-video-api"
echo ""

echo "Backup data:"
echo "  ./deployment/backup.sh"
echo ""

echo "View config:"
echo "  cat deployment/deploy.conf"
echo ""

echo "Get API key:"
echo "  cat /var/www/fastapi-video-api/.env | grep SESSION_SECRET"
echo ""

echo "EMERGENCY RECOVERY:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If server crashes and you need a new one, use this ONE command:"
echo ""
echo "  git clone https://github.com/YOUR_USERNAME/apiXVideo /var/www/apiXVideo && \\"
echo "  cd /var/www/apiXVideo && \\"
echo "  chmod +x deployment/*.sh && \\"
echo "  sudo ./deployment/deploy_openlitespeed.sh --fast"
echo ""
echo "Result: Complete redeploy in 5 minutes! ✅"
echo ""

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║                    ✨ YOU ARE NOW FULLY DEPLOYED! ✨                      ║"
echo "║                                                                            ║"
echo "║  Your API is running, secured, and ready for production!                  ║"
echo "║  You can redeploy to any new server in 5 minutes anytime!                 ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""
